### ISSUE TITLE
working of savana cna calling

### ISSUE THREAD

**Issue by sachingadakh** [cortes-ciriano-lab/savana#44]
Hello,
   Thank you for your suggestion on my previous issue #42. As per your suggestion in #42 , I ran the "savana cna" with the following command and received this error. Should I perform SV calling and phasing?  However, I cannot because I do not have a normal sample, right?
Besides, you had asked about the coverage and average read length in issue #42 . The coverage is around 1.23X by samtools depth and 1X by mosdepth. The average read size is 1.1 kb. 

savana cna -t ../methyalation_data/dorado_meth_data/tumor.bam --outdir /disk2/ONT_files/ONT_methylation_analysis/CNV_data/savana/ --ref ../hg38.fa -w 1
Source: /home/rakieta/anaconda3/lib/python3.11/site-packages/savana/savana.py

... Allele counter will use threads = 24. (threads = 48 defined; threads = 24 available) ...
    Extracting phased heterozygous SNPs from None ...
Traceback (most recent call last):
  File "/home/rakieta/anaconda3/bin/savana", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/rakieta/anaconda3/lib/python3.11/site-packages/savana/savana.py", line 496, in main
    args.func(args)
  File "/home/rakieta/anaconda3/lib/python3.11/site-packages/savana/savana.py", line 193, in savana_cna
    allele_counts_bed_path = allele_counter.perform_allele_counting(outdir, args.sample, args.phased_vcf, args.tumour, args.allele_mapq, args.allele_min_reads, args.threads)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rakieta/anaconda3/lib/python3.11/site-packages/savana/allele_counter.py", line 150, in perform_allele_counting
    het_snps = extract_hets(phased_vcf)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rakieta/anaconda3/lib/python3.11/site-packages/savana/allele_counter.py", line 24, in extract_hets
    vcf_reader = cyvcf2.VCF(phased_vcf)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "cyvcf2/cyvcf2.pyx", line 278, in cyvcf2.cyvcf2.VCF.__init__
  File "cyvcf2/cyvcf2.pyx", line 205, in cyvcf2.cyvcf2.HTSFile._open_htsfile
OSError: Cannot open '<class 'NoneType'>' for writing.

**Comment by cmsauer** [comment]
Sorry, I think my previous answer was a bit misleading. It seems that your data is inappropriate for this approach. For reliable SV and SCNA calling, you need whole genome (not adaptive sampling) sequencing data at ideally ~20-30X (or higher) with matched normal sequencing data available too. Unfortunately, you seem to have shallow sequencing data, and no matched normal. Hope this makes sense! Carolin
