### ISSUE TITLE
Dependency on unzipping models into install directory causes biocontainers to not work

### ISSUE THREAD

**Issue by oneillkza** [cortes-ciriano-lab/savana#54]
Hi there,

The way we usually run bioinformatics software in our centre is to use Docker containers from the Biocontainers project, via singularity/apptainer.

The Biocontainers project automatically builds these containers from Bioconda packages. You can see the Savana containers built from the Savana bioconda package here: https://quay.io/repository/biocontainers/savana

This is the only place I'm aware of that hosts containers for Savana.

The issue is that Savana wants to unzip model files at runtime, which is fundamentally incompatible with containers being a read-only file system. I'm guessing conda installs to a location that's user-writeable, which is why this works just via conda itself. But it feels like making changes to an install at runtime is still a little dangerous (and, as in this case, can break downstream functionality like the containerization provided by Biocontainers). 

In general, the solution would be not to modify the install directory at runtime. Some ways around this might be:

- Just don't gzip the model files? They're pretty small.
- Keep the models gzipped, but unzip into memory at runtime (again, they're pretty small, so could be done at each run).
- Keep the models gzipped, but unzip into, but znzip into the temp directory at runtime.
- Provide your own container that does a dummy run at build time to force the unzipping of the model files, so the read-only state of the container is ready for further runs. (This might end up being our short-term workaround.)

Steps to reproduce:

```
apptainer pull docker://quay.io/biocontainers/savana:1.2.4--pyhdfd78af_0
apptainer exec -B /projects savana_1.2.4--pyhdfd78af_0.sif savana \
  --tumour ONT_COLO829_N_truthset_50k.phased.bam \
  --normal ONT_COLO829_T_truthset_50k.phased.bam \
  --outdir ./test \
  --ref hg38_no_alt.fa
```

And you get output like so:

```

███████  █████  ██    ██  █████  ███    ██  █████
██      ██   ██ ██    ██ ██   ██ ████   ██ ██   ██
███████ ███████ ██    ██ ███████ ██ ██  ██ ███████
     ██ ██   ██  ██  ██  ██   ██ ██  ██ ██ ██   ██
███████ ██   ██   ████   ██   ██ ██   ████ ██   ██

Version 1.2.4
Source: /usr/local/lib/python3.11/site-packages/savana/savana.py

Running as sample ONT_COLO829_N_truthset_50k.phased
Found hg38_no_alt.fa.fai to use as reference fasta index
Using 144 thread(s)

Identified potential breakpoints                            20.675 seconds
 > 19 clustering tasks
Clustered potential breakpoints                             3.725 seconds
 > 19 calling tasks
Called consensus breakpoints                                4.723 seconds
 > 404 depth annotation tasks
Annotated breakpoints with depth and phasing                6.647 seconds
404 annotated breakpoints to output
Output consensus breakpoints                                0.823 seconds
Total time to call raw variants                             38.823 seconds

Using ONT model to classify variants
First time using model - will untar /usr/local/lib/python3.11/site-packages/savana/models/ont-somatic.tar.gz
Traceback (most recent call last):
  File "/usr/local/bin/savana", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/savana/savana.py", line 516, in main
    args.func(args)
  File "/usr/local/lib/python3.11/site-packages/savana/savana.py", line 242, in savana_main
    savana_classify(args)
  File "/usr/local/lib/python3.11/site-packages/savana/savana.py", line 125, in savana_classify
    tar.extractall(models_dir)
  File "/usr/local/lib/python3.11/tarfile.py", line 2294, in extractall
    self._extract_one(tarinfo, path, set_attrs=not tarinfo.isdir(),
  File "/usr/local/lib/python3.11/tarfile.py", line 2361, in _extract_one
    self._handle_fatal_error(e)
  File "/usr/local/lib/python3.11/tarfile.py", line 2357, in _extract_one
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
  File "/usr/local/lib/python3.11/tarfile.py", line 2440, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/local/lib/python3.11/tarfile.py", line 2486, in makefile
    with bltn_open(targetpath, "wb") as target:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/usr/local/lib/python3.11/site-packages/savana/models/ont-somatic.pkl'

```

Thanks for your time and help with this!

**Comment by oneillkza** [comment]
Thank you so much for the speedy response, @helrick!
 
That should solve things for us once things propagate through.

For the longer term, if the model does grow again, it seems to me that it should be fine to download it at install time? Another option would be to use Git LFS. https://github.com/git-lfs/git-lfs
